# Generated by Django 3.0.4 on 2020-04-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Fruit'), ('V', 'Vegetables'), ('M', 'Meat')], default='V', max_length=2),
        ),
    ]
