# Generated by Django 3.0.4 on 2020-04-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('D', 'Discount'), ('O', 'Out of stock'), ('', '')], default='', max_length=1),
        ),
    ]
