# Generated by Django 3.0.4 on 2020-04-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20200402_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Fruit'), ('V', 'Vegetables'), ('M', 'Meat'), ('MK', 'Milk'), ('G', 'Grocery')], max_length=2),
        ),
    ]
